### ISSUE TITLE
Catch fetch errors or allow overwrite fetch

### ISSUE THREAD

**Issue by bkniffler** [axiomhq/axiom-js#131]
Getting this error during log ingestion:

```
FetchError: request to https://api.axiom.co/v1/datasets/..../ingest failed, reason: getaddrinfo ENOTFOUND api.axiom.co
```

This is causing unhandled promise rejection with the automatic flushing. 

I'd suggest we get some option to capture this, e.g.
```
const axiom = new Axiom({
  token: '...',
  orgId: '...',
  fetch: async (a, b) => fetch(a, b).catch(() => ..)
  // or
  handleError: () => ....
});
```

**Comment by schehata** [comment]
I am working on handling those exception now, finalizing the [PR](https://github.com/axiomhq/axiom-js/pull/144).

**Comment by bkniffler** [comment]
Hey, thanks @schehata, it did indeed solve my problem, I'm using `onError` to suppress errors, thanks!
