### ISSUE TITLE
Crashes in browser on process in packages/js/src/httpClient.ts if not setting url

### ISSUE THREAD

**Issue by bobmoff** [axiomhq/axiom-js#24]
Trying to use Axiom for a Vue project, but it crashes on on launch if i don't set the url option.

If I set it to the default value, it works. 

```
const axiom = new Axiom({ token: 'XXX', orgId: 'XXX', url: 'https://api.axiom.co' })
```

```process``` is not available in the browser. Thats why it fails on line 17 in httpClient.

```
const url = options.url || process.env.AXIOM_URL || AxiomURL;
```

Not sure how to solve this, thats why I am creating an issue instead of a PR.

**Comment by bahlo** [comment]
Hi @bobmoff, thanks for the issue! I'm faking `process.env` in #26 and thinking about how to better catch these issues in the future 🙌

**Comment by bahlo** [comment]
All depending on if there's anything to release. There'll be one today  😎

**Comment by bahlo** [comment]
@bobmoff Can you try again with 0.1.2?

**Comment by bobmoff** [comment]
Works! 🥳
