### ISSUE TITLE
Typescript configs extends "non existing" file

### ISSUE THREAD

**Issue by bobmoff** [axiomhq/axiom-js#25]
in file packages/js/tsconfig.json

```
"extends": "../../tsconfig.base.json",
```

this assumes I have this file inside my node_modules folder.

**Comment by bahlo** [comment]
Hi @bobmoff, do you get an error when installing/using the library?

**Comment by bobmoff** [comment]
Hmm, no I actually dont any more. Thats weird. Ok. Sorry.
