### ISSUE TITLE
`process` fake interferes with polyfills

### ISSUE THREAD

**Issue by qin-guan** [axiomhq/axiom-js#55]
The fake for `process` below:

https://github.com/axiomhq/axiom-js/blob/main/packages/pino/src/index.ts#L5-L6

Interferes with the polyfills when bundling an app.

### Reproduction

https://codesandbox.io/p/sandbox/axiomhq-pino-edge-repro-ypv4xm?file=%2Fserver%2Fmiddleware%2Flogger.ts%3A13%2C53

To build for non-node environment (polyfilled): 

```shell
NITRO_PRESET=netlify-edge pnpm build
```

To build for node environment (without polyfills): 

```shell
pnpm build
```

When building for non-node environments, `process` is polyfilled but results in Rollup error.

**Comment by schehata** [comment]
I have faced errors with this as well on the edge runtime for the e2e app in the repo. Trying to think of a better workaround.

**Comment by schehata** [comment]
Hi, We have a released a new version that fixes this build issue. It's still `rc` but maybe [you could give it a try](https://www.npmjs.com/package/@axiomhq/js/v/1.0.0-rc.1).
