### ISSUE TITLE
Does this support React Native?

### ISSUE THREAD

**Issue by AdamMomen** [axiomhq/axiom-js#61]
I'm wondering if I can use axiom on a react native mobile app? I really like axiom and hope I can find a way to keep using it on my projects.

Has anybody been able to do that before?

**Comment by schehata** [comment]
hi Adam, well, we havent tried this with react native before, but I assume sending logs to Axiom should work just fine, does nextjs work with react native? if yes can you give this library a try and if there is any issues we will help you with it. if not, then probably axiom-js is the right tool for the job.

**Comment by ha-sante** [comment]
@dasfmi  ERROR  [TypeError: AbortSignal.timeout is not a function (it is undefined)]


It does not and logging library also fails to apply the error colors etc.

**Comment by ha-sante** [comment]
@dasfmi  Added a polyfill and that fixed it.


random script that might help somehow:


    if (typeof global.AbortSignal !== 'undefined' && typeof global.AbortSignal.timeout !== 'function') {
      global.AbortSignal.timeout = function timeout(ms) {
        const controller = new AbortController();
        setTimeout(() => controller.abort(), ms);
        return controller.signal;
      };
    }
