### ISSUE TITLE
Cannot install `@axiomhq/pino` via pnpm

### ISSUE THREAD

**Issue by alexng353** [axiomhq/axiom-js#70]
ERR_PNPM_LINKING_FAILED  Error: EPERM: operation not permitted, copyfile 'C:\Users\alexn\AppData\Local\pnpm\store\v3\files\6d\94c89501f0d2646d764df6975ec5a5ed6d7b149bc78a112acacbd52cb79863bed9804a373795cb48f2fb7b36715801a9e0b8a4fe5b0fbbafb4f2435d615ab2' -> 'C:\Users\alexn\Documents\Code\EduBeyond\node_modules\.pnpm\@axiomhq+pino@0.1.3\node_modules\@axiomhq\pino_tmp_26376\.turbo\turbo-build:esm.log'

**Comment by alexng353** [comment]
The issue seems to be that there is an invalid character in the path, but I can't figure out how to remedy this.

**Comment by alexng353** [comment]
Closing because the fix for this is as follows:

1. close vscode
2. open another terminal 
3. install

**Comment by ImLunaHey** [comment]
Cause: https://github.com/vercel/turbo/issues/317

**Comment by adcorduneanu** [comment]
ERR_PNPM_LINKING_FAILED - Maybe for you, this happens on the local system but for others, this happens in the build agents
