### ISSUE TITLE
Named export 'Axiom' not found. The requested module '@axiomhq/js' is a CommonJS module

### ISSUE THREAD

**Issue by yaronlevi** [axiomhq/axiom-js#72]
Following the official docs and getting this error:

![CleanShot 2023-09-10 at 18 18 51@2x](https://github.com/axiomhq/axiom-js/assets/5398977/96296e98-565c-44ae-ae22-ac9a41c3efb9)

Any idea what might cause this?

**Comment by yaronlevi** [comment]
Also, if I try this import I get this error:

![CleanShot 2023-09-10 at 18 26 32@2x](https://github.com/axiomhq/axiom-js/assets/5398977/aea17732-d296-4cf3-80ba-685b4984a98c)

**Comment by tmak** [comment]
Currently, `@axiomhq/js` is unusable via ESM.

The following changes in `packages/js/package.json` would fix this:
- Add `"type": "module"`
- Change `"default": "./dist/cjs/index.js"` to `"default": "./dist/esm/index.js"`

That's how `package.json` for the `pino` and `winston` packages are configured. Is there any reason not to do the same for the `js` package?

**Comment by schehata** [comment]
Hi we have a released a new version that fixes this build issue. It's still `rc` but maybe [you could give it a try](https://www.npmjs.com/package/@axiomhq/js/v/1.0.0-rc.1).

**Comment by schehata** [comment]
should be fixed, feel free to open again if you are still facing the same issue.
