### ISSUE TITLE
Can't import WinstonTransport 

### ISSUE THREAD

**Issue by pyrexfm** [axiomhq/axiom-js#80]
### Problem
Tried to import WinstonTransport and it didn't work (using "@axiomhq/winston": "^0.1.3"). 

### Workaround 
I went to the index.ts file inside node modules and found this error:
![image](https://github.com/axiomhq/axiom-js/assets/73044172/60d6911b-324d-470e-bd89-2bdbd75a8ff8)

> Module '"c:/Users/franc/ReactProjects/wealth-tracker/node_modules/winston-transport/index"' can only be default-imported using the 'esModuleInterop' flagts(1259)

I went to the package tsconfig and added `esModuleInterop:true` and it still doesn't run.

**Comment by schehata** [comment]
Hi @pyrexfm we have a released a new version that fixes this build issue. It's still `rc` but maybe [you could give it a try](https://www.npmjs.com/package/@axiomhq/js/v/1.0.0-rc.1).

**Comment by pyrexfm** [comment]
It's fixed, thank you
